// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"pxx-server/ioc"
	"pxx-server/repository"
	"pxx-server/repository/dao"
	"pxx-server/service"
	"pxx-server/web"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitGinMiddlewares()
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	handleUser := web.NewUserHandle(userService)
	engine := ioc.InitWebServer(v, handleUser)
	return engine
}
